### ISSUE TITLE
Proposal: Store Non-Deflated Sources

### ISSUE THREAD

**Issue by sashokbg** [maciek365/c4-diagrams.net#7]
Hello, I have a proposal to change some things within the project.
Please let me know what you think and if its OK with you we can start a draft PR and create a POC:

**Currently**
it is hard to maintain the elements and shapes within the project since everything is mashed-up in a single XML file with encoded entries.

**Proposal**
- Extract the encoded XML entries in a non-encoded format (like using https://jgraph.github.io/drawio-tools/tools/convert.html).
- Extract the SVG path shapes in separate files
- Add js tooling that encodes and combines everything in a final dist (production) version
- Add a pipeline that publishes the dist version

**Benefits**
- Allows to easily edit and modify existing entities
- Allows to add new shapes easily
- Newcomers can quickly see where things are coming from
- Can improve auto-documentation and probably remove the need to add a .png example to show the shapes

**Drawbacks**
- Includes some complexity to the project

**Comment by maciek365** [comment]
Sounds great but unfortunately, I can't join to work on your proposal within the next few months because of a lack of free time :-(

I see that you have great ideas related to this tool, so you need to know that some time ago my library has been incorporated into diagrams.net/draw.io apps and it is currently available as a standard built-in library (since diagrams.net v15.5.4 -> https://github.com/jgraph/drawio/compare/v15.5.2...v15.5.4).
You can use it after selecting "C4" from the menu "+ More shapes..." (in the bottom left corner).

I think that probably a better idea is to make an effort to develop this library within the diagrams.net project -> https://github.com/jgraph/drawio
Probably this approach will make your ideas for improving this C4 library will be available to more potential users as a standard build-in plugin within the diagrams.net application :-)

I'll keep my fingers crossed for developing and improving this tool.

Maciek

**Comment by sashokbg** [comment]
Hello Maciek,

Thank you for your reply. I can completely relate to the feeling of being overwhelmed with work x).
Thank you for the suggestions, I will go take a look at the jgraph repository.

Best Regards,
Alexander
